symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600 # Durée de validité du lien de réinitialisation du mot de passe en secondes (1 heure)
    throttle_limit: 3 # Nombre maximal de demandes de réinitialisation de mot de passe autorisées par heure
